export type MevzuatCatalogEntry = {
    no: string;
    title: string;
    abbrev: string[];
    turCandidates?: number[];
};

export const MEVZUAT_CATALOG: MevzuatCatalogEntry[] = [
    { no: '2709', title: 'Türkiye Cumhuriyeti Anayasası', abbrev: ['Anayasa', 'AY'] },
    { no: '1136', title: 'Avukatlık Kanunu', abbrev: ['AvK'] },
    { no: '1512', title: 'Noterlik Kanunu', abbrev: [] },
    { no: '7201', title: 'Tebligat Kanunu', abbrev: ['TebK'] },
    { no: '4982', title: 'Bilgi Edinme Hakkı Kanunu', abbrev: [] },
    { no: '6754', title: 'Bilirkişilik Kanunu', abbrev: [] },
    { no: '4721', title: 'Türk Medeni Kanunu', abbrev: ['TMK'] },
    {
        no: '6284',
        title: 'Ailenin Korunması ve Kadına Karşı Şiddetin Önlenmesine Dair Kanun',
        abbrev: [],
    },
    { no: '5490', title: 'Nüfus Hizmetleri Kanunu', abbrev: [] },
    { no: '6698', title: 'Kişisel Verilerin Korunması Kanunu', abbrev: ['KVKK'] },
    { no: '5253', title: 'Dernekler Kanunu', abbrev: [] },
    { no: '5737', title: 'Vakıflar Kanunu', abbrev: [] },
    { no: '6098', title: 'Türk Borçlar Kanunu', abbrev: ['TBK'] },
    { no: '6102', title: 'Türk Ticaret Kanunu', abbrev: ['TTK'] },
    { no: '6502', title: 'Tüketicinin Korunması Hakkında Kanun', abbrev: ['TKHK'] },
    {
        no: '7155',
        title: 'Abonelik Sözleşmesinden Kaynaklanan Para Alacaklarına İlişkin Takibin Başlatılması Usulü Hakkında Kanun',
        abbrev: ['MTS Kanunu'],
    },
    { no: '5941', title: 'Çek Kanunu', abbrev: [] },
    { no: '2920', title: 'Türk Sivil Havacılık Kanunu', abbrev: [] },
    { no: '6362', title: 'Sermaye Piyasası Kanunu', abbrev: ['SPK'] },
    { no: '6563', title: 'Elektronik Ticaretin Düzenlenmesi Hakkında Kanun', abbrev: [] },
    { no: '4857', title: 'İş Kanunu', abbrev: ['İşK'] },
    {
        no: '5510',
        title: 'Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu',
        abbrev: ['SSGSSK'],
    },
    { no: '4447', title: 'İşsizlik Sigortası Kanunu', abbrev: [] },
    { no: '7036', title: 'İş Mahkemeleri Kanunu', abbrev: [] },
    { no: '6331', title: 'İş Sağlığı ve Güvenliği Kanunu', abbrev: ['İSGK'] },
    { no: '6356', title: 'Sendikalar ve Toplu İş Sözleşmesi Kanunu', abbrev: [] },
    { no: '5237', title: 'Türk Ceza Kanunu', abbrev: ['TCK'] },
    { no: '5271', title: 'Ceza Muhakemesi Kanunu', abbrev: ['CMK'] },
    {
        no: '5235',
        title: 'Adlî Yargı İlk Derece Mahkemeleri ile Bölge Adliye Mahkemelerinin Kuruluş, Görev ve Yetkileri Hakkında Kanun',
        abbrev: [],
    },
    {
        no: '5402',
        title: 'Denetimli Serbestlik ve Yardım Merkezleri ile Koruma Kurulları Kanunu',
        abbrev: ['Denetimli Serbestlik Kanunu'],
    },
    { no: '5275', title: 'Ceza ve Güvenlik Tedbirlerinin İnfazı Hakkında Kanun', abbrev: ['CGTİHK'] },
    { no: '5326', title: 'Kabahatler Kanunu', abbrev: [] },
    { no: '5395', title: 'Çocuk Koruma Kanunu', abbrev: ['ÇKK'] },
    { no: '5607', title: 'Kaçakçılıkla Mücadele Kanunu', abbrev: [] },
    {
        no: '5651',
        title: 'İnternet Ortamında Yapılan Yayınların Düzenlenmesi ve Bu Yayınlar Yoluyla İşlenen Suçlarla Mücadele Edilmesi Hakkında Kanun',
        abbrev: ['İnternet Kanunu'],
    },
    { no: '634', title: 'Kat Mülkiyeti Kanunu', abbrev: ['KMK'] },
    { no: '3194', title: 'İmar Kanunu', abbrev: [] },
    {
        no: '6306',
        title: 'Afet Riski Altındaki Alanların Dönüştürülmesi Hakkında Kanun',
        abbrev: [],
    },
    { no: '2644', title: 'Tapu Kanunu', abbrev: [] },
    { no: '2942', title: 'Kamulaştırma Kanunu', abbrev: [] },
    { no: '4342', title: 'Mera Kanunu', abbrev: [] },
    { no: '2985', title: 'Toplu Konut Kanunu', abbrev: [] },
    { no: '3402', title: 'Kadastro Kanunu', abbrev: [] },
    { no: '2872', title: 'Çevre Kanunu', abbrev: [] },
    { no: '6100', title: 'Hukuk Muhakemeleri Kanunu', abbrev: ['HMK'] },
    { no: '2004', title: 'İcra ve İflas Kanunu', abbrev: ['İİK'] },
    { no: '2577', title: 'İdari Yargılama Usulü Kanunu', abbrev: ['İYUK'] },
    {
        no: '2576',
        title: 'Bölge İdare Mahkemeleri, İdare Mahkemeleri ve Vergi Mahkemelerinin Kuruluşu ve Görevleri Hakkında Kanun',
        abbrev: [],
    },
    { no: '6325', title: 'Hukuk Uyuşmazlıklarında Arabuluculuk Kanunu', abbrev: ['HUAK'] },
    { no: '2918', title: 'Karayolları Trafik Kanunu', abbrev: ['KTK'] },
    { no: '1593', title: 'Umumi Hıfzıssıhha Kanunu', abbrev: [] },
    { no: '657', title: 'Devlet Memurları Kanunu', abbrev: ['DMK'] },
    { no: '6183', title: 'Amme Alacaklarının Tahsil Usulü Hakkında Kanun', abbrev: ['AATUHK'] },
    { no: '213', title: 'Vergi Usul Kanunu', abbrev: ['VUK'] },
    { no: '4734', title: 'Kamu İhale Kanunu', abbrev: ['KİK'] },
    { no: '5018', title: 'Kamu Malî Yönetimi ve Kontrol Kanunu', abbrev: [] },
    { no: '2464', title: 'Belediye Gelirleri Kanunu', abbrev: [] },
    { no: '5393', title: 'Belediye Kanunu', abbrev: [] },
    { no: '492', title: 'Harçlar Kanunu', abbrev: [] },
    { no: '5846', title: 'Fikir ve Sanat Eserleri Kanunu', abbrev: ['FSEK'] },
    { no: '6769', title: 'Sınaî Mülkiyet Kanunu', abbrev: ['SMK'] },
    { no: '5070', title: 'Elektronik İmza Kanunu', abbrev: [] },
    {
        no: '6216',
        title: 'Anayasa Mahkemesinin Kuruluşu ve Yargılama Usulleri Hakkında Kanun',
        abbrev: [],
    },
    { no: '2797', title: 'Yargıtay Kanunu', abbrev: [] },
    { no: '2575', title: 'Danıştay Kanunu', abbrev: [] },
    { no: '2802', title: 'Hakimler ve Savcılar Kanunu', abbrev: ['HSK'] },
    { no: '5411', title: 'Bankacılık Kanunu', abbrev: [] },
    { no: '5464', title: 'Banka Kartları ve Kredi Kartları Kanunu', abbrev: [] },
    {
        no: '6493',
        title: 'Ödeme ve Menkul Kıymet Mutabakat Sistemleri, Ödeme Hizmetleri ve Elektronik Para Kuruluşları Hakkında Kanun',
        abbrev: [],
    },
    { no: '4054', title: 'Rekabetin Korunması Hakkında Kanun', abbrev: [] },
    { no: '5684', title: 'Sigortacılık Kanunu', abbrev: [] },
    {
        no: '6361',
        title: 'Finansal Kiralama, Faktoring, Finansman ve Tasarruf Finansman Şirketleri Kanunu',
        abbrev: [],
    },
    { no: '6750', title: 'Ticari İşlemlerde Taşınır Rehni Kanunu', abbrev: [] },
    { no: '854', title: 'Deniz İş Kanunu', abbrev: [] },
    { no: '5953', title: 'Basın Mesleğinde Çalışanlarla Çalıştıranlar Arasındaki Münasebetlerin Tanzimi Hakkında Kanun', abbrev: ['Basın İş Kanunu'] },
    { no: '4688', title: 'Kamu Görevlileri Sendikaları ve Toplu Sözleşme Kanunu', abbrev: [] },
    { no: '3713', title: 'Terörle Mücadele Kanunu', abbrev: ['TMK-Terör'] },
    { no: '6136', title: 'Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanun', abbrev: [] },
    { no: '2559', title: 'Polis Vazife ve Salahiyet Kanunu', abbrev: ['PVSK'] },
    { no: '3628', title: 'Mal Bildiriminde Bulunulması, Rüşvet ve Yolsuzluklarla Mücadele Kanunu', abbrev: [] },
    { no: '5549', title: 'Suç Gelirlerinin Aklanmasının Önlenmesi Hakkında Kanun', abbrev: [] },
    { no: '4686', title: 'Milletlerarası Tahkim Kanunu', abbrev: [] },
    { no: '5718', title: 'Milletlerarası Özel Hukuk ve Usul Hukuku Hakkında Kanun', abbrev: ['MÖHUK'] },
    { no: '193', title: 'Gelir Vergisi Kanunu', abbrev: ['GVK'] },
    { no: '5520', title: 'Kurumlar Vergisi Kanunu', abbrev: ['KVK'] },
    { no: '3065', title: 'Katma Değer Vergisi Kanunu', abbrev: ['KDVK', 'KDV'] },
    { no: '488', title: 'Damga Vergisi Kanunu', abbrev: [] },
    { no: '4735', title: 'Kamu İhale Sözleşmeleri Kanunu', abbrev: [] },
    { no: '2886', title: 'Devlet İhale Kanunu', abbrev: [] },
    { no: '5216', title: 'Büyükşehir Belediyesi Kanunu', abbrev: [] },
    { no: '5442', title: 'İl İdaresi Kanunu', abbrev: [] },
    { no: '6831', title: 'Orman Kanunu', abbrev: [] },
    { no: '3621', title: 'Kıyı Kanunu', abbrev: [] },
    { no: '5403', title: 'Toprak Koruma ve Arazi Kullanımı Kanunu', abbrev: [] },
    { no: '3213', title: 'Maden Kanunu', abbrev: [] },
    { no: '6458', title: 'Yabancılar ve Uluslararası Koruma Kanunu', abbrev: ['YUKK'] },
    { no: '5901', title: 'Türk Vatandaşlığı Kanunu', abbrev: [] },
    { no: '6735', title: 'Uluslararası İşgücü Kanunu', abbrev: [] },
    { no: '4875', title: 'Doğrudan Yabancı Yatırımlar Kanunu', abbrev: [] },
    { no: '5682', title: 'Pasaport Kanunu', abbrev: [] },
    { no: '7338', title: 'Veraset ve İntikal Vergisi Kanunu', abbrev: [] },
    { no: '1319', title: 'Emlak Vergisi Kanunu', abbrev: [] },
    { no: '4458', title: 'Gümrük Kanunu', abbrev: [] },
    { no: '4760', title: 'Özel Tüketim Vergisi Kanunu', abbrev: ['ÖTVK'] },
    { no: '4925', title: 'Karayolları Taşıma Kanunu', abbrev: [] },
    { no: '6446', title: 'Elektrik Piyasası Kanunu', abbrev: [] },
    { no: '5015', title: 'Petrol Piyasası Kanunu', abbrev: [] },
    { no: '5187', title: 'Basın Kanunu', abbrev: [] },
    { no: '6112', title: 'Radyo ve Televizyonların Kuruluş ve Yayın Hizmetleri Hakkında Kanun', abbrev: ['RTÜK Kanunu'] },
    { no: '1219', title: 'Tababet ve Şuabatı San’atlarının Tarzı İcrasına Dair Kanun', abbrev: [] },
    { no: '3359', title: 'Sağlık Hizmetleri Temel Kanunu', abbrev: [] },
    { no: '2547', title: 'Yükseköğretim Kanunu', abbrev: [] },
    { no: '7405', title: 'Spor Kulüpleri ve Spor Federasyonları Kanunu', abbrev: [] },
    { no: '3218', title: 'Serbest Bölgeler Kanunu', abbrev: [] },
    { no: '4562', title: 'Organize Sanayi Bölgeleri Kanunu', abbrev: [] },
    { no: '4691', title: 'Teknoloji Geliştirme Bölgeleri Kanunu', abbrev: [] },
    { no: '6585', title: 'Perakende Ticaretin Düzenlenmesi Hakkında Kanun', abbrev: [] },
    { no: '5346', title: 'Yenilenebilir Enerji Kaynaklarının Elektrik Enerjisi Üretimi Amaçlı Kullanımına İlişkin Kanun', abbrev: [] },
    { no: '5686', title: 'Jeotermal Kaynaklar ve Doğal Mineralli Sular Kanunu', abbrev: [] },
    { no: '5300', title: 'Tarım Ürünleri Lisanslı Depoculuk Kanunu', abbrev: [] },
    { no: '2863', title: 'Kültür ve Tabiat Varlıklarını Koruma Kanunu', abbrev: [] },
    { no: '2634', title: 'Turizmi Teşvik Kanunu', abbrev: [] },
    { no: '2873', title: 'Milli Parklar Kanunu', abbrev: [] },
    { no: '5199', title: 'Hayvanları Koruma Kanunu', abbrev: [] },
    { no: '197', title: 'Motorlu Taşıtlar Vergisi Kanunu', abbrev: ['MTVK'] },
    { no: '6802', title: 'Gider Vergileri Kanunu', abbrev: [] },
    { no: '7194', title: 'Dijital Hizmet Vergisi ile Bazı Kanunlarda ve 375 Sayılı Kanun Hükmünde Kararnamede Değişiklik Yapılması Hakkında Kanun', abbrev: ['DHV'] },
    { no: '210', title: 'Değerli Kağıtlar Kanunu', abbrev: [] },
    { no: '2820', title: 'Siyasi Partiler Kanunu', abbrev: ['SPK-Siyasi'] },
    { no: '5188', title: 'Özel Güvenlik Hizmetlerine Dair Kanun', abbrev: [] },
    { no: '5543', title: 'İskân Kanunu', abbrev: [] },
    { no: '7269', title: 'Umumi Hayata Müessir Afetler Dolayısiyle Alınacak Tedbirlerle Yapılacak Yardımlara Dair Kanun', abbrev: [] },
    { no: '5302', title: 'İl Özel İdaresi Kanunu', abbrev: [] },
    { no: '2911', title: 'Toplantı ve Gösteri Yürüyüşleri Kanunu', abbrev: [] },
    {
        no: '2548',
        title: 'Ceza Evleri ile Mahkeme Binaları İnşası Karşılığı Olarak Alınacak Harçlar ve Mahkûmlara Ödettirilecek Yiyecek Bedelleri Hakkında Kanun',
        abbrev: [],
    },
    { no: '5996', title: 'Veteriner Hizmetleri, Bitki Sağlığı, Gıda ve Yem Kanunu', abbrev: [] },
    { no: '5488', title: 'Tarım Kanunu', abbrev: [] },
    { no: '1380', title: 'Su Ürünleri Kanunu', abbrev: [] },
    { no: '4915', title: 'Kara Avcılığı Kanunu', abbrev: [] },
    {
        no: '7464',
        title: 'Konutların Turizm Amaçlı Kiralanması Hakkında Kanun',
        abbrev: ['Turizm Kiralaması Kanunu'],
    },
    { no: '1618', title: 'Seyahat Acentaları ve Seyahat Acentaları Birliği Kanunu', abbrev: [] },
    { no: '6326', title: 'Turist Rehberliği Meslek Kanunu', abbrev: [] },
    { no: '1163', title: 'Kooperatifler Kanunu', abbrev: [] },
    {
        no: '5174',
        title: 'Türkiye Odalar ve Borsalar Birliği ile Odalar ve Borsalar Kanunu',
        abbrev: ['TOBB Kanunu'],
    },
    {
        no: '5957',
        title: 'Sebze ve Meyve Ticareti ve Toptancı Halleri Hakkında Kanun',
        abbrev: ['Hal Kanunu'],
    },
    { no: '7223', title: 'Ürün Güvenliği ve Teknik Düzenlemeler Kanunu', abbrev: [] },
    {
        no: '1567',
        title: 'Türk Parasının Kıymetini Koruma Hakkında Kanun',
        abbrev: ['TPKK'],
    },
    { no: '1262', title: 'İspençiyari ve Tıbbi Müstahzarlar Kanunu', abbrev: [] },
    { no: '4646', title: 'Doğal Gaz Piyasası Kanunu', abbrev: [] },
    { no: '5809', title: 'Elektronik Haberleşme Kanunu', abbrev: [] },
    {
        no: '663',
        title: 'Sağlık Bakanlığı ve Bağlı Kuruluşlarının Teşkilat ve Görevleri Hakkında Kanun Hükmünde Kararname',
        abbrev: ['KHK 663'],
        turCandidates: [4],
    },
    {
        no: '1',
        title: 'Cumhurbaşkanlığı Teşkilatı Hakkında Cumhurbaşkanlığı Kararnamesi',
        abbrev: ['CBK 1', '1 sayılı CBK'],
        turCandidates: [19],
    },
];


export const MEVZUAT_SEARCH_ALIASES: Readonly<Record<string, readonly string[]>> = {
    '6098': ['borçlar', 'borçlar kanunu', 'türk borçlar', 'türk borçlar kanunu'],
    '4721': ['medeni', 'medeni kanun', 'türk medeni', 'türk medeni kanunu'],
    '5237': ['ceza', 'ceza kanunu', 'türk ceza', 'türk ceza kanunu'],
    '6102': ['ticaret', 'ticaret kanunu', 'türk ticaret', 'türk ticaret kanunu'],
    '6100': ['hukuk muhakemeleri', 'hukuk muhakemeleri kanunu', 'hukuk usulü'],
    '5271': ['ceza muhakemesi', 'ceza muhakemesi kanunu', 'ceza usulü'],
    '2004': ['icra iflas', 'icra ve iflas', 'icra iflas kanunu', 'icra ve iflas kanunu', 'icra'],
    '2577': ['idari yargılama', 'idari yargılama usulü', 'idari yargılama usulü kanunu'],
    '213': ['vergi usul', 'vergi usul kanunu'],
    '1136': ['avukatlık', 'avukatlık kanunu'],
    '1512': ['noterlik', 'noterlik kanunu'],
    '7201': ['tebligat', 'tebligat kanunu'],
    '4857': ['iş kanunu', 'is kanunu'],
    '5326': ['kabahatler', 'kabahatler kanunu'],
    '4447': ['işsizlik sigortası', 'işsizlik sigortası kanunu'],
    '5464': ['kredi kartı', 'banka kartları', 'kredi kartları kanunu', 'banka kartları kanunu'],
    '6493': ['ödeme sistemleri', 'elektronik para', 'ödeme hizmetleri'],
    '4342': ['mera', 'mera kanunu'],
    '2985': ['toplu konut', 'toki', 'toplu konut kanunu'],
    '2576': ['idare mahkemeleri', 'vergi mahkemeleri kuruluş', 'bölge idare mahkemeleri'],
    '5018': ['kamu mali yönetimi', 'kamu mali yönetimi ve kontrol'],
    '2464': ['belediye gelirleri', 'belediye gelirleri kanunu'],
    '5235': ['adli yargı kuruluş', 'bölge adliye mahkemeleri kuruluş'],
    '5402': ['denetimli serbestlik', 'denetimli serbestlik kanunu'],
    '7155': ['merkezi takip', 'mts', 'abonelik takip', 'e-takip'],
    '2911': ['toplantı ve gösteri', 'gösteri yürüyüşleri'],
    '5302': ['il özel idaresi', 'il özel idaresi kanunu'],
    '5996': ['gıda ve yem', 'veteriner hizmetleri', 'tağşiş'],
    '7464': ['turizm amaçlı kiralama', 'airbnb', 'kısa dönem kiralama'],
    '6326': ['turist rehberliği', 'turist rehberliği meslek kanunu'],
    '1163': ['kooperatifler', 'kooperatifler kanunu'],
    '5174': ['tobb', 'odalar ve borsalar'],
    '5957': ['hal kanunu', 'sebze ve meyve ticareti', 'toptancı halleri'],
    '7223': ['ürün güvenliği', 'teknik düzenlemeler'],
    '1567': ['kambiyo', 'türk parasının kıymetini koruma', 'tpkk'],
    '5809': ['elektronik haberleşme', 'btk'],
    '4646': ['doğal gaz piyasası', 'doğalgaz'],
    '663': ['sağlık bakanlığı teşkilat', 'khk 663'],
    '1': ['cumhurbaşkanlığı kararnamesi', 'cbk 1', '1 sayılı kararname'],
};

export function catalogSearchAliases(no: string): readonly string[] {
    return MEVZUAT_SEARCH_ALIASES[no] ?? [];
}

export type MevzuatYonetmelikCatalogEntry = MevzuatCatalogEntry & {
    /** Official MevzuatTur values to probe (4 = Yönetmelik/KHK, 7 = Kurum Yönetmeliği, 9 = Tebliğ, 19 = CBK, 21 = CB Yönetmeliği, 2 = Tüzük). */
    turCandidates: number[];
};

/**
 * Focused lawyer-relevant yönetmelikler / tüzük / tebliğ. Numbers come from
 * mevzuat.gov.tr iframe URLs (not invented). Generate skips any that do not resolve.
 * Tur: 7 then 4 for kurum/bakanlık yönetmeliği; 21 CB yönetmeliği; 9 tebliğ/tarife; 2 tüzük.
 */
export const YONETMELIK_CATALOG: MevzuatYonetmelikCatalogEntry[] = [
    {
        no: '15828',
        title: 'Tebligat Kanununun Uygulanmasına Dair Yönetmelik',
        abbrev: ['TebYön', 'Tebligat Yönetmeliği'],
        turCandidates: [7, 4],
    },
    {
        no: '23615',
        title: 'Bölge Adliye ve Adlî Yargı İlk Derece Mahkemeleri ile Cumhuriyet Başsavcılıkları İdarî ve Yazı İşleri Hizmetlerinin Yürütülmesine Dair Yönetmelik',
        abbrev: ['HMKYön', 'Yazı İşleri Yönetmeliği'],
        turCandidates: [7, 4],
    },
    {
        no: '38760',
        title: 'Hukuk Muhakemelerinde Ses ve Görüntü Nakledilmesi Yoluyla Duruşma İcrası Hakkında Yönetmelik',
        abbrev: ['e-Duruşma'],
        turCandidates: [7, 4],
    },
    {
        no: '8043',
        title: 'İcra ve İflâs Kanunu Yönetmeliği',
        abbrev: ['İİKYön', 'İİK Yönetmeliği'],
        turCandidates: [7, 4],
    },
    {
        no: '5780',
        title: 'Türkiye Barolar Birliği Avukatlık Kanunu Yönetmeliği',
        abbrev: ['AvYön', 'TBB Yönetmeliği'],
        turCandidates: [7, 4],
    },
    {
        no: '5040',
        title: 'Noterlik Kanunu Yönetmeliği',
        abbrev: ['NoterYön'],
        turCandidates: [7, 4],
    },
    {
        no: '7076',
        title: 'Adlî Tıp Kurumu Kanunu Uygulama Yönetmeliği',
        abbrev: ['AdliTıpYön'],
        turCandidates: [7, 4],
    },
    {
        no: '23818',
        title: 'Bilirkişilik Yönetmeliği',
        abbrev: ['BilirkişiYön'],
        turCandidates: [7, 4],
    },
    {
        no: '24638',
        title: 'Hukuk Uyuşmazlıklarında Arabuluculuk Kanunu Yönetmeliği',
        abbrev: ['ArabuluculukYön', 'HUAKYön'],
        turCandidates: [7, 4],
    },
    {
        no: '12459',
        title: 'Alt İşverenlik Yönetmeliği',
        abbrev: ['AltİşverenYön'],
        turCandidates: [7, 4],
    },
    {
        no: '5451',
        title: 'Yıllık Ücretli İzin Yönetmeliği',
        abbrev: ['İzinYön'],
        turCandidates: [7, 4],
    },
    {
        no: '5447',
        title: 'İş Kanununa İlişkin Çalışma Süreleri Yönetmeliği',
        abbrev: ['ÇalışmaSüreleriYön'],
        turCandidates: [7, 4],
    },
    {
        no: '31556',
        title: 'Abonelik Sözleşmesinden Kaynaklanan Para Alacaklarına İlişkin Takibin Başlatılması Usulü Hakkında Yönetmelik',
        abbrev: ['MTSYön', 'E-Takip Yönetmeliği'],
        turCandidates: [7, 4],
    },
    {
        no: '23722',
        title: 'Planlı Alanlar İmar Yönetmeliği',
        abbrev: ['İmarYön'],
        turCandidates: [7, 4],
    },
    {
        no: '20135150',
        title: 'Tapu Sicili Tüzüğü',
        abbrev: ['TapuTüz'],
        turCandidates: [2],
    },
    {
        no: '3935',
        title: 'Devlet Memurları Disiplin Yönetmeliği',
        abbrev: ['DisiplinYön'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '8197',
        title: 'Yakalama, Gözaltına Alma ve İfade Alma Yönetmeliği',
        abbrev: ['YakalamaYön'],
        turCandidates: [7, 4],
    },
    {
        no: '8203',
        title: 'Adlî ve Önleme Aramaları Yönetmeliği',
        abbrev: ['AramaYön'],
        turCandidates: [7, 4],
    },
    {
        no: '24038',
        title: 'Kişisel Verilerin Silinmesi, Yok Edilmesi veya Anonim Hale Getirilmesi Hakkında Yönetmelik',
        abbrev: ['KVKKSilmeYön'],
        turCandidates: [7, 4],
    },
    {
        no: '2324',
        title: 'Ceza İnfaz Kurumlarının Yönetimi ile Ceza ve Güvenlik Tedbirlerinin İnfazı Hakkında Yönetmelik',
        abbrev: ['İnfazYön'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '41015',
        title: 'Avukatlık Asgari Ücret Tarifesi',
        abbrev: ['AAÜT'],
        turCandidates: [9, 7, 4],
    },
    {
        no: '20059207',
        title: 'İşyeri Açma ve Çalışma Ruhsatlarına İlişkin Yönetmelik',
        abbrev: ['İşyeri Ruhsat Yön.'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '39647',
        title: 'Çevresel Etki Değerlendirmesi Yönetmeliği',
        abbrev: ['ÇED Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '11951',
        title: 'Yapı Denetimi Uygulama Yönetmeliği',
        abbrev: ['Yapı Denetim Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '31300',
        title: 'Şantiye Şefleri Hakkında Yönetmelik',
        abbrev: ['Şantiye Şefi Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '39077',
        title: 'Orman Kanununun 17 nci Maddesinin Üçüncü Fıkrasının Uygulanması Hakkında Yönetmelik',
        abbrev: ['Orman 17/3 Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '15592',
        title: 'Gıda Hijyeni Yönetmeliği',
        abbrev: ['Gıda Hijyeni Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '31251',
        title: 'Arazi Toplulaştırması ve Tarla İçi Geliştirme Hizmetleri Uygulama Yönetmeliği',
        abbrev: ['Toplulaştırma Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '1134',
        title: 'Turizm Tesislerinin Belgelendirilmesine ve Niteliklerine İlişkin Yönetmelik',
        abbrev: ['Turizm Tesis Yön.'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '9171',
        title: 'Koruma Amaçlı İmar Planları ve Çevre Düzenleme Projelerinin Hazırlanması, Gösterimi, Uygulaması, Denetimi ve Müelliflerine İlişkin Usul ve Esaslara Ait Yönetmelik',
        abbrev: ['Koruma Amaçlı İmar Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '11648',
        title: 'Seyahat Acentaları Yönetmeliği',
        abbrev: ['Seyahat Acentası Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '20124093',
        title: 'Ticaret Sicili Yönetmeliği',
        abbrev: ['Ticaret Sicili Yön.'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '19819',
        title: 'Fiyat Etiketi Yönetmeliği',
        abbrev: ['Etiket Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '20237',
        title: 'Mesafeli Sözleşmeler Yönetmeliği',
        abbrev: ['Mesafeli Sözleşme Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '40940',
        title: 'Motorlu Kara Taşıtlarının Ticareti Hakkında Yönetmelik',
        abbrev: ['İkinci El Taşıt Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '24645',
        title: 'Taşınmaz Ticareti Hakkında Yönetmelik',
        abbrev: ['Emlak Ticareti Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '16924',
        title: 'İş Sağlığı ve Güvenliği Hizmetleri Yönetmeliği',
        abbrev: ['İSG Hizmetleri Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '15452',
        title: 'Vergi İncelemelerinde Uyulacak Usul ve Esaslar Hakkında Yönetmelik',
        abbrev: ['Vergi İnceleme Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '12916',
        title: 'Yapım İşleri İhaleleri Uygulama Yönetmeliği',
        abbrev: ['Yapım İhale Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '200713012',
        title: 'Suç Gelirlerinin Aklanmasının ve Terörün Finansmanının Önlenmesine Dair Tedbirler Hakkında Yönetmelik',
        abbrev: ['MASAK Tedbirler Yön.'],
        turCandidates: [21, 7, 4],
    },
    {
        no: '4847',
        title: 'Hasta Hakları Yönetmeliği',
        abbrev: ['Hasta Hakları Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '41265',
        title: 'Özel Hastaneler Yönetmeliği',
        abbrev: ['Özel Hastane Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '42369',
        title: 'Ayakta Teşhis ve Tedavi Yapılan Özel Sağlık Kuruluşları Hakkında Yönetmelik',
        abbrev: ['Ayakta Teşhis Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '38657',
        title: 'Tıbbi Cihaz Yönetmeliği',
        abbrev: ['Tıbbi Cihaz Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '24299',
        title: 'Karayolu Taşıma Yönetmeliği',
        abbrev: ['K1/K2 Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '31502',
        title: 'Elektrik Piyasasında Lisanssız Elektrik Üretim Yönetmeliği',
        abbrev: ['Lisanssız Üretim Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '5454',
        title: 'Asgari Ücret Yönetmeliği',
        abbrev: ['Asgari Ücret Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '13354',
        title: 'Kamu İhale Genel Tebliği',
        abbrev: ['KİK Genel Tebliği'],
        turCandidates: [9, 7, 4],
    },
    {
        no: '39873',
        title: 'Maden Yönetmeliği',
        abbrev: ['Maden Yön.'],
        turCandidates: [7, 4],
    },
    {
        no: '15958',
        title: 'Korunması Gerekli Taşınmaz Kültür Varlıklarının ve Sitlerin Tespit ve Tescili Hakkında Yönetmelik',
        abbrev: ['Kültür Varlığı Tescil Yön.'],
        turCandidates: [7, 4],
    },
];

export type BundledMevzuatCatalogEntry = {
    kind: 'kanun' | 'yonetmelik';
    no: string;
    title: string;
    abbrev: string[];
    turCandidates: number[];
};

export function bundledMevzuatCatalog(): BundledMevzuatCatalogEntry[] {
    const kanun: BundledMevzuatCatalogEntry[] = MEVZUAT_CATALOG.map((row) => ({
        kind: 'kanun',
        no: row.no,
        title: row.title,
        abbrev: row.abbrev,
        turCandidates: row.turCandidates ?? [1],
    }));
    const yonetmelik: BundledMevzuatCatalogEntry[] = YONETMELIK_CATALOG.map((row) => ({
        kind: 'yonetmelik',
        no: row.no,
        title: row.title,
        abbrev: row.abbrev,
        turCandidates: row.turCandidates,
    }));
    return [...kanun, ...yonetmelik];
}

export function catalogShortName(entry: { title: string; abbrev: string[] }): string {
    return entry.abbrev[0] || entry.title;
}
