import type { ShortcutRegistryEntry } from './types';

/**
 * Canonical shortcut catalog for documentation and UI hints.
 * App-level handlers: `useAppKeyboardShortcuts`; editor: Tiptap extensions + dedicated hooks.
 */
export const SHORTCUT_REGISTRY: ShortcutRegistryEntry[] = [
    // —— Global / shell ——
    {
        id: 'command-palette',
        actionTr: 'Komut paleti (arama)',
        scope: 'global',
        combo: { mod: true, key: 'k' },
        implementation: 'CommandPalette.tsx',
        notesTr: 'Açıkken tekrar basınca kapanır.',
    },
    {
        id: 'command-palette-templates',
        actionTr: 'Komut paleti — şablonlar sekmesi',
        scope: 'global',
        combo: { mod: true, shift: true, key: 's' },
        implementation: 'CommandPalette.tsx',
    },
    {
        id: 'command-palette-katir',
        actionTr: 'Komut paleti — Katır',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'k' },
        implementation: 'CommandPalette.tsx',
        notesTr: 'Katır (UYAP) sekmesini açar.',
    },
    {
        id: 'command-palette-tasks',
        actionTr: 'Komut paleti — Yapılacaklar',
        scope: 'global',
        combo: { mod: true, shift: true, key: 't' },
        implementation: 'CommandPalette.tsx',
        notesTr: 'Görev listesi; tarihli görevler Takvim aynasına yazılır.',
    },
    {
        id: 'new-document',
        actionTr: 'Yeni belge sekmesi',
        scope: 'global',
        combo: { mod: true, key: 'n' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Form alanı veya komut paleti açıkken çalışmaz.',
    },
    {
        id: 'new-note',
        actionTr: 'Yeni not',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'n' },
        implementation: 'useAppKeyboardShortcuts.ts',
    },
    {
        id: 'close-active-tab',
        actionTr: 'Aktif sekmeyi kapat',
        scope: 'global',
        combo: { mod: true, key: 'w' },
        implementation: 'useAppKeyboardShortcuts.ts / closeActiveTab.ts',
        notesTr: 'Yalnızca odaktaki Dockview sekmesini kapatır; form alanı veya komut paleti açıkken çalışmaz.',
    },
    {
        id: 'toggle-file-explorer',
        actionTr: 'Dosya gezgini aç/kapat',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'e' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Form alanı veya komut paleti açıkken çalışmaz.',
    },
    {
        id: 'focus-or-open-viewer',
        actionTr: 'Görüntüleyiciye odaklan/aç',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'v' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Editör/form odaktayken devre dışı (Mod+Shift+V = düz metin yapıştır).',
    },
    {
        id: 'open-comments-panel',
        actionTr: 'Yorumlar paneli',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'c' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Yorumlar flyout panelini açar.',
    },
    {
        id: 'zen-mode-toggle',
        actionTr: 'Zen modu aç/kapa',
        scope: 'global',
        combo: { mod: true, shift: true, key: 'm' },
        implementation: 'useZenModeKeyboard.ts',
    },
    {
        id: 'zen-mode-exit',
        actionTr: 'Zen modundan çık',
        scope: 'global',
        combo: { key: 'Escape' },
        implementation: 'useZenModeKeyboard.ts',
        notesTr: 'Yalnızca zen modunda; açık modal varken çalışmaz.',
    },
    {
        id: 'udf-save',
        actionTr: 'UDF kaydet',
        scope: 'global',
        combo: { mod: true, key: 's' },
        implementation: 'UdfFileEditorPanel.tsx',
        notesTr: 'UDF sekmesi açıkken; aktif panelde kayıt tetikler.',
    },
    {
        id: 'udf-save-as',
        actionTr: 'UDF farklı kaydet',
        scope: 'global',
        combo: { mod: true, alt: true, key: 's' },
        implementation: 'UdfFileEditorPanel.tsx',
        notesTr: 'UDF dosya sekmesi açıkken; yeni konuma kaydeder ve sekmeyi yeni dosyaya taşır. ⌘⇧S şablonlar paletine aittir.',
    },
    {
        id: 'database-search-matters',
        actionTr: 'Dosyalar aramasını aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '1' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Dosyalar flyout panelini açar ve arama kutusuna odaklanır; ana editör odaktayken Tiptap paragraf stili kazanır.',
    },
    {
        id: 'database-search-parties',
        actionTr: 'Taraflar aramasını aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '2' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Taraflar flyout panelini açar ve arama kutusuna odaklanır; ana editör odaktayken Tiptap paragraf stili kazanır.',
    },
    {
        id: 'database-search-knowledge',
        actionTr: 'Bilgi Bankası aramasını aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '3' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Bilgi Bankası flyout panelini açar ve arama kutusuna odaklanır; ana editör odaktayken Tiptap paragraf stili kazanır.',
    },
    {
        id: 'database-search-notes',
        actionTr: 'Notlar aramasını aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '4' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Notlar flyout panelini açar ve arama kutusuna odaklanır; ana editör odaktayken Tiptap paragraf stili kazanır.',
    },
    {
        id: 'database-open-calendar',
        actionTr: 'Takvim panelini aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '5' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Takvim flyout panelini açar/kapatır; ana editör odaktayken Tiptap H5 varsayılan kaydı kazanır.',
    },
    {
        id: 'database-search-mevzuat',
        actionTr: 'Mevzuat aramasını aç',
        scope: 'global',
        combo: { mod: true, alt: true, key: '6' },
        implementation: 'useAppKeyboardShortcuts.ts',
        notesTr: 'Mevzuat flyout panelini açar ve arama kutusuna odaklanır; ana editör odaktayken Tiptap H6 varsayılan kaydı kazanır.',
    },

    // —— UdfixEditor (window / hook) ——
    {
        id: 'editor-find',
        actionTr: 'Belgede bul',
        scope: 'editor-search',
        combo: { mod: true, key: 'f' },
        implementation: 'useUdfixEditorSearchAndHistoryShortcuts.ts',
    },
    {
        id: 'editor-version-history',
        actionTr: 'Sürüm geçmişi',
        scope: 'editor',
        combo: { mod: true, shift: true, key: 'h' },
        implementation: 'useUdfixEditorSearchAndHistoryShortcuts.ts',
    },
    {
        id: 'editor-search-close',
        actionTr: 'Arama panelini kapat',
        scope: 'editor-search',
        combo: { key: 'Escape' },
        implementation: 'useUdfixEditorSearchAndHistoryShortcuts.ts',
    },
    {
        id: 'editor-find-next-in-doc',
        actionTr: 'Sonraki eşleşme (arama açıkken, editör gövdesi)',
        scope: 'editor-search',
        combo: { key: 'Enter' },
        implementation: 'useUdfixEditorSearchAndHistoryShortcuts.ts',
    },
    {
        id: 'editor-find-prev-in-doc',
        actionTr: 'Önceki eşleşme (arama açıkken, editör gövdesi)',
        scope: 'editor-search',
        combo: { shift: true, key: 'Enter' },
        implementation: 'useUdfixEditorSearchAndHistoryShortcuts.ts',
    },
    {
        id: 'paste-match-destination',
        actionTr: 'Hedef stile uygun düz metin yapıştır',
        scope: 'editor',
        combo: { mod: true, shift: true, key: 'v' },
        implementation: 'UdfixEditor.tsx',
    },

    // —— Viewer ——
    {
        id: 'viewer-find',
        actionTr: 'Görüntüleyicide ara',
        scope: 'viewer',
        combo: { mod: true, key: 'f' },
        implementation: 'UniversalViewer.tsx',
    },
    {
        id: 'viewer-search-close',
        actionTr: 'Görüntüleyici aramasını kapat',
        scope: 'viewer',
        combo: { key: 'Escape' },
        implementation: 'UniversalViewer.tsx',
    },

    // —— Tiptap (StarterKit + extensions) ——
    {
        id: 'tiptap-undo',
        actionTr: 'Geri al',
        scope: 'tiptap',
        combo: { mod: true, key: 'z' },
        implementation: '@tiptap/starter-kit',
    },
    {
        id: 'tiptap-redo',
        actionTr: 'Yinele',
        scope: 'tiptap',
        combo: { mod: true, shift: true, key: 'z' },
        implementation: '@tiptap/starter-kit',
    },
    {
        id: 'tiptap-bold',
        actionTr: 'Kalın',
        scope: 'tiptap',
        combo: { mod: true, key: 'b' },
        implementation: 'ListMarkerFormat.ts',
        notesTr: 'Liste işaretinde NodeSelection varsa işaret biçimi.',
    },
    {
        id: 'tiptap-italic',
        actionTr: 'İtalik',
        scope: 'tiptap',
        combo: { mod: true, key: 'i' },
        implementation: 'ListMarkerFormat.ts',
    },
    {
        id: 'tiptap-underline',
        actionTr: 'Altı çizili',
        scope: 'tiptap',
        combo: { mod: true, key: 'u' },
        implementation: 'ListMarkerFormat.ts',
    },
    {
        id: 'tiptap-page-break',
        actionTr: 'Sayfa sonu ekle',
        scope: 'tiptap',
        combo: { mod: true, key: 'Enter' },
        implementation: 'BreakShortcuts.ts',
    },
    {
        id: 'tiptap-footnote',
        actionTr: 'Dipnot ekle',
        scope: 'tiptap',
        combo: { mod: true, shift: true, key: 'f' },
        implementation: 'FootnoteExtension.ts',
    },
    {
        id: 'tiptap-paragraph-normal',
        actionTr: 'Paragraf stili varsayılanını kaydet — normal',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '0' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-1',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 1',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '1' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-2',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 2',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '2' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-3',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 3',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '3' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-4',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 4',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '4' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-5',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 5',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '5' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-heading-6',
        actionTr: 'Paragraf stili varsayılanını kaydet — Başlık 6',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '6' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-title-style',
        actionTr: 'Paragraf stili varsayılanını kaydet — belge başlığı',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '7' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-subtitle-style',
        actionTr: 'Paragraf stili varsayılanını kaydet — alt başlık',
        scope: 'tiptap',
        combo: { mod: true, alt: true, key: '8' },
        implementation: 'ParagraphStyleShortcuts.ts',
    },
    {
        id: 'tiptap-tab-indent',
        actionTr: 'Girinti / liste içe al',
        scope: 'tiptap',
        combo: { key: 'Tab' },
        implementation: 'SmartIndent.ts',
        notesTr: 'Listede sink; paragrafta UYAP uyumlu tek sekme karakteri.',
    },
    {
        id: 'tiptap-tab-outdent',
        actionTr: 'Girinti azalt / liste dışa al',
        scope: 'tiptap',
        combo: { shift: true, key: 'Tab' },
        implementation: 'SmartIndent.ts',
    },
    {
        id: 'tiptap-variable-next',
        actionTr: 'Sonraki değişken yuvası',
        scope: 'tiptap',
        combo: { key: 'Tab' },
        implementation: 'VariableSlot.ts',
        notesTr: 'Değişken yuvası varken SmartIndent yerine öncelikli.',
    },
    {
        id: 'tiptap-variable-prev',
        actionTr: 'Önceki değişken yuvası',
        scope: 'tiptap',
        combo: { shift: true, key: 'Tab' },
        implementation: 'VariableSlot.ts',
    },

    // —— Search panel UI ——
    {
        id: 'search-panel-find-next',
        actionTr: 'Sonraki eşleşme (arama kutusu)',
        scope: 'panel',
        combo: { key: 'Enter' },
        implementation: 'SearchPanel.tsx',
    },
    {
        id: 'search-panel-find-prev',
        actionTr: 'Önceki eşleşme (arama kutusu)',
        scope: 'panel',
        combo: { shift: true, key: 'Enter' },
        implementation: 'SearchPanel.tsx',
    },
    {
        id: 'search-panel-replace',
        actionTr: 'Değiştir (tek)',
        scope: 'panel',
        combo: { key: 'Enter' },
        implementation: 'SearchPanel.tsx',
        notesTr: 'Değiştir satırında.',
    },
    {
        id: 'search-panel-replace-all',
        actionTr: 'Tümünü değiştir',
        scope: 'panel',
        combo: { mod: true, key: 'Enter' },
        implementation: 'SearchPanel.tsx',
        notesTr: 'Değiştir satırında.',
    },

    // —— Panels / overlays ——
    {
        id: 'hf-panel-close',
        actionTr: 'Üst/alt bilgi panelini kapat',
        scope: 'panel',
        combo: { key: 'Escape' },
        implementation: 'HeaderFooterPanel.tsx',
    },
    {
        id: 'version-history-close',
        actionTr: 'Sürüm geçmişi panelini kapat',
        scope: 'panel',
        combo: { key: 'Escape' },
        implementation: 'VersionHistoryPanel.tsx',
    },

    // —— Suggestion popovers ——
    {
        id: 'mention-escape',
        actionTr: '@ öneri listesini kapat',
        scope: 'popover',
        combo: { key: 'Escape' },
        implementation: 'suggestion.ts / NoteEditor',
    },
    {
        id: 'template-hash-nav',
        actionTr: '## şablon önerisi — ok tuşları / Enter',
        scope: 'popover',
        combo: { key: 'ArrowUp' },
        notesTr: 'ArrowDown ve Enter ile seçim; Escape ile kapatma.',
        implementation: 'textTemplateSuggestion.ts',
    },
];

export function getRegistryEntry(id: string): ShortcutRegistryEntry | undefined {
    return SHORTCUT_REGISTRY.find((e) => e.id === id);
}
